---
- hosts: windows_2016
  tasks:
    - name: Ensure IIS is enabled
      win_feature:
        name: Web-Server
        state: present
      
    - name: Ensure that there is no binding on HTTP port
      win_iis_webbinding:
        name: Default Web Site
        port: 80
        state: absent
      when: sn_u_iis_https_exception == 'false'
    - name: Ensure that there is the binding on HTTPS port
      win_iis_webbinding:
        name: Default Web Site
        protocol: https
        port: 443
        certificate_hash: ''
      when: sn_u_iis_https_exception == 'false'
    - name: Ensure that there is the binding on HTTP port
      win_iis_webbinding:
        name: Default Web Site
        port: 80
      when: sn_u_iis_https_exception == 'true'
    - name: Ensure that there is no binding on HTTPS port
      win_iis_webbinding:
        name: Default Web Site
        protocol: https
        port: 443
        certificate_hash: ''
        state: absent
      when: sn_u_iis_https_exception == 'true'
